# Generated by Django 5.2.13 on 2026-04-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='scanner/originals/')),
                ('scanned_image', models.ImageField(blank=True, null=True, upload_to='scanner/results/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='scanner/pdfs/')),
                ('ocr_text', models.TextField(blank=True)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('document_confidence', models.FloatField(default=0)),
                ('fake_risk_score', models.FloatField(default=0)),
                ('fake_risk_level', models.CharField(blank=True, max_length=50)),
                ('fake_reasons', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
