# Generated by Django 5.2.13 on 2026-04-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='boundary_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='classification_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='manual_review_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='ocr_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='quality_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
